# Generated by Django 5.0.4 on 2024-11-23 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='public_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255),
        ),
    ]
