# Generated by Django 5.0.4 on 2024-11-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_utilisateur_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='public_key',
            field=models.TextField(),
        ),
    ]
