# Generated by Django 5.0.4 on 2024-11-23 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_utilisateur_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='public_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=1000),
        ),
    ]
